### ISSUE TITLE
Mongo and memcache 

### ISSUE THREAD

**Issue by rhnkyr** [desarrolla2/Cache#11]
I try to store fetched data from mongo in memcache. But it throws error.

So i changed get and set functions in Desarrolla2\Cache\Adapter\MemCache\MemCache.php file to

 /**
     * {@inheritdoc }
     */
    public function get($key)
    {
        $tKey = $this->getKey($key);
        $data = $this->server->get($tKey);
        if (!is_array($data))
            return $this->unserialize($data);
        else
            return $data;

    }

    /**
     * {@inheritdoc }
     */
    public function set($key, $value, $ttl = null)
    {

        $tKey = $this->getKey($key);

        if (!is_array($value))
            $tValue = $this->serialize($value);
        else
            $tValue = $value;

        if (!$ttl) {
            $ttl = $this->ttl;
        }
        $this->server->set($tKey, $tValue, time() + $ttl);
    }

maybe you can change ur file as mines. Btw thank you for your great lib.

**Comment by khromov** [comment]
@desarrolla2 How about now? :-)

**Comment by desarrolla2** [comment]
This was solved
