### ISSUE TITLE
has() in File adapter false negative

### ISSUE THREAD

**Issue by benswinburne** [desarrolla2/Cache#21]
The `has()` method in the File adapter fails if the value is there but `false`/`null`/`0` etc.

    public function has($key)
    {
        if (!$this->getData($key)) {
            return false;
        }
        return true;
    }

`getData($key)` can exist and then return false (or equivalent) but this causes a false negative when determining if there's a value in the cache.

**Comment by desarrolla2** [comment]
i am working on this.
