### ISSUE TITLE
Mongo adapter v2

### ISSUE THREAD

**Issue by jasny** [desarrolla2/Cache#25]
The [Mongo adapter](https://github.com/desarrolla2/Cache/blob/1.8/src/Adapter/Mongo.php) is no longer present in v2.

Note that the `Mongo` class has been deprecated instead the `MongoClient`/`MongoDB` class should be used.

**Comment by jasny** [comment]
I can create a pull request if you like.

**Comment by desarrolla2** [comment]
sure!
