### ISSUE TITLE
Setup server host

### ISSUE THREAD

**Issue by nums** [desarrolla2/Cache#28]
For example, when memcache server is not on the same server than php script.
We have to do this 
```php
$memcache = new \Memcache();
$memcache->addServer('XX.XX.XX.XX', 11211);
$adapter = new \Desarrolla2\Cache\Adapter\Memcache($memcache);
```
and maybe delete this line in the constructor :
```php
$this->server->addServer('localhost', 11211);
```

**Comment by jasny** [comment]
@desarrolla2 This issue is invalid.

You can already pass a `Memcache` object when creating an adapter. The `addServer` is only done when you omit the argument in constructor.
