### ISSUE TITLE
File implementation TTL and cleanup

### ISSUE THREAD

**Issue by aaronpeterson** [desarrolla2/Cache#31]
The File adapter has no cleanup for TTL.  As such, everything lives on the file system forever.  Somewhat surprised to see my cache dir grow to 1.3G.  I'd like to contribute something here but not sure if anyone has any input.  Perhaps a cleanup probability during set()?  Somewhat similar to php's own garbage collection probability?

Or perhaps support implementing their own Cleanup interface for now?

**Comment by desarrolla2** [comment]
You can implement cleanup methods for FileAdapter, and final user, will be use as he want, i will recomend use it on command line, for example on cron job.

Please send PR

**Comment by jasny** [comment]
Running a cron job might not be possible if you're on a shared hosting environment. An alternative is to [register a shutdown function](http://php.net/manual/en/function.register-shutdown-function.php), which flushes the output and closes the connection. Than let the PHP script continue and clean the files.

See http://php.net/manual/en/features.connection-handling.php#71172
