### ISSUE TITLE
Bug in Version 1.8.0

### ISSUE THREAD

**Issue by antoniogarcia78** [desarrolla2/Cache#33]
In the File.php - Line 100 you use short array notation and the composer required 5.3.3. Short notation appear in 5.4 no?

Otherwise work awesome

**Comment by desarrolla2** [comment]
yes, can you send a PR?

**Comment by echernyavskiy** [comment]
@desarrolla2 I raised https://github.com/desarrolla2/Cache/pull/36 hoping that you could cut 1.8.2 for those still stuck w/ PHP 5.3. Can you take a look?

**Comment by jasny** [comment]
@echernyavskiy Done
