### ISSUE TITLE
Move away from adapter / wrapper

### ISSUE THREAD

**Issue by jasny** [desarrolla2/Cache#40]
The [Cache](https://github.com/desarrolla2/Cache/blob/master/src/Cache.php) class is a wrapper around an adapter. It doesn't seem to have any benefit.

Instead we can rename the adapters and change them to implement PSR-16. That way they can be used directly.

```php
use Dessarolla2\Cache;

$cache = new Cache\Apu();
```

**Comment by jasny** [comment]
@desarrolla2 I can create a PR for this, but it would mean breaking BC, so a new full version (v3.0). Are you cool with that?

**Comment by desarrolla2** [comment]
ok

**Comment by jasny** [comment]
Solved in v3
