### ISSUE TITLE
Add PHP file caching

### ISSUE THREAD

**Issue by jasny** [desarrolla2/Cache#41]
We can leverage opcode caching to create a very fast caching method in PHP 7+. 

To set the cache use `var_export` to get the value as PHP code and than write that to a PHP file. 
To get the cache simply use `include`.

Read more about it in [this article](https://blog.graphiq.com/500x-faster-caching-than-redis-memcache-apc-in-php-hhvm-dcd26e8447ad).

**Comment by stevevance** [comment]
I really like this idea. I wish that the blog post you linked to @jasny had a bit more code, though, so we could start implementing that concept right away.

**Comment by jasny** [comment]
Implemented in v3
