### ISSUE TITLE
Database for cache.

### ISSUE THREAD

**Issue by ngoyal16** [desarrolla2/Cache#48]
What is the mysql database structure you have used for cache in mysql database.

**Comment by ngoyal16** [comment]
@desarrolla2

**Comment by ngoyal16** [comment]
CREATE TABLE `cache` (
  `k` varchar(255) NOT NULL,
  `v` text NOT NULL,
  `t` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `cache`
  ADD PRIMARY KEY (`k`) USING BTREE;

**Comment by desarrolla2** [comment]
Great work @ngoyal16.

Can you send a PR for documentation?
