### ISSUE TITLE
Not abandoning the project

### ISSUE THREAD

**Issue by jasny** [desarrolla2/Cache#71]
@desarrolla2 Unfortunately, v3 (the PSR-16 implementation I worked on) hasn't caught on. In the meantime, other implementations like http://www.php-cache.com are widely used.

It doesn't seem worth it to continue working on this project. New projects better switch to another PSR-16 compatible library. Old projects can continue using v2, even if the project is abandoned.

I'm also closing all the issues with features I planned to add.

**Comment by desarrolla2** [comment]
ok @jasny thanks for your all work!

**Comment by jasny** [comment]
![screenshot-packagist org-2019 03 15-15-59-38](https://user-images.githubusercontent.com/100821/54440631-61be1300-473b-11e9-93d3-8f814f1ff82f.png)

![giphy](https://user-images.githubusercontent.com/100821/54440720-8dd99400-473b-11e9-93d4-8bb86a03ad95.gif)

**Comment by jasny** [comment]
@desarrolla2 There's been a big switch from v2 to v3 last month. With 1.5k+ downloads per day, I'll keep maintaining this project.
 
![screenshot-packagist org-2020 05 11-11_21_52](https://user-images.githubusercontent.com/100821/81545766-a2cea900-9379-11ea-8630-13769c098ac5.png)

**Comment by desarrolla2** [comment]
very good news!
