### ISSUE TITLE
Scrutinizer build broken

### ISSUE THREAD

**Issue by jasny** [desarrolla2/Cache#75]
![screenshot-scrutinizer-ci com-2020 05 11-11_16_18](https://user-images.githubusercontent.com/100821/81545221-dc52e480-9378-11ea-8cf9-05b3cbe2d6aa.png)

**Comment by jasny** [comment]
@desarrolla2 Can you please give my access to this project in Scrutinizer CI?

**Comment by desarrolla2** [comment]
![image](https://user-images.githubusercontent.com/661529/81700683-4c409800-9469-11ea-8139-af1d54f164b9.png)

Done!
