### ISSUE TITLE
Uncaught Error: Cannot use object of type stdClass as array in vendor/desarrolla2/cache/src/MongoDB.php on line 102

### ISSUE THREAD

**Issue by miklcct** [desarrolla2/Cache#84]
I have stored a MongoDB\BSON\Persistable into the MongoDB cache with default settings. However, when trying to retrieve it, it throws the error "Cannot use object of type stdClass as array"

**Comment by jasny** [comment]
By default, the data is serialized (using `serialize()`) and stored as BSON binary.

Try using the `NopPacker`. If that doesn't work, you might need to create a custom packer.
